FROM node

WORKDIR /usr/app

COPY ./package.json .
COPY ./yarn.lock .
COPY ./packages/web/ ./packages/web/
COPY ./packages/common/package.json ./packages/common/
COPY ./packages/common/dist ./packages/common/dist

RUN npm i -g yarn
RUN yarn install

WORKDIR ./packages/web

ENV NODE_ENV=production

EXPOSE 3000

CMD [ "yarn", "start" ]