FROM node

WORKDIR /usr/app

COPY ./package.json .
COPY ./packages/web/ ./packages/web/
COPY ./packages/common/package.json ./packages/common/

RUN npm i -g yarn
RUN yarn install --production

COPY ./packages/common/dist ./packages/common/dist

WORKDIR ./packages/web

ENV NODE_ENV=production

EXPOSE 3000

CMD [ "yarn", "start" ]