FROM node

WORKDIR /usr/app

COPY ./package.json .
COPY ./lerna.json .
COPY ./packages/web/ ./packages/web/
COPY ./packages/common/ ./packages/common/

RUN npm i -g yarn
RUN yarn install
RUN yarn build:web

WORKDIR ./packages/web

ENV NODE_ENV=production

EXPOSE 3000

CMD [ "yarn", "start" ]